### ISSUE TITLE
Try source tree

### ISSUE THREAD

**Issue by messana** [acamargo213/Rate_your_Attorney#4]
Not a code-specific task, but download source tree as a front end to git and see if it helps visualize the branch/merge workflow.  Once you have a chance to test it, please update this issue with whether or not you found it valuable.  If you prefer the command line, why?  If you prefer source tree, why?

Once the team has updated this issue, it will be closed.

**Comment by aangott** [comment]
I did some exploring, and it looks like SourceTree won't work with your Cloud 9 development environment.  That's ok -- we can do git on the command line.  I'm here to help with whatever you need, and things will start making more sense as you get more practice.
